GECCLA_DIR = /home/romang/scripts/geccla

CONLL_NUCLE_M2 = /home/romang/data/nucle/nucle.m2

CONLL_TEST2013_M2 = /home/romang/data/nucle/nucle.test2013.m2
CONLL_TEST2014_M2 = /home/romang/data/nucle/nucle.test2014.m2

LANG8_NAIST = /home/romang/data/lang8/lang8-naist.nltktok.clean.txt


# LANG8 NAIST
lang8.cor: $(LANG8_NAIST)
	cut -f2 $? > $@
lang8.err: $(LANG8_NAIST)
	cut -f1 $? > $@

# TEST2014
test2014.cor: test2014.txt
	cut -f2 $? > $@
test2014.err: test2014.txt
	cut -f1 $? > $@

test2014.txt: test2014.m2
	cat $? | $(GECCLA_DIR)/scripts/make_parallel.perl > $@
test2014.m2:
	cat $(CONLL_TEST2014_M2) > $@

clean-test2014:
	rm -f test2014.txt test2014.err test2014.cor

# TEST2013
test2013.cor: test2013.txt
	cut -f2 $? > $@
test2013.err: test2013.txt
	cut -f1 $? > $@

test2013.txt: test2013.m2
	cat $? | $(GECCLA_DIR)/scripts/make_parallel.perl > $@
test2013.m2:
	cat $(CONLL_TEST2013_M2) > $@

clean-test2013:
	rm -f test2013.txt test2013.err test2013.cor

# NUCLE
nucle.cor: nucle.txt
	cut -f2 $? > $@
nucle.err: nucle.txt
	cut -f1 $? > $@

nucle.txt: nucle.m2
	cat $? | $(GECCLA_DIR)/scripts/make_parallel.perl > $@
nucle.m2:
	cat $(CONLL_NUCLE_M2) > $@

clean-nucle:
	rm -f nucle.txt nucle.err nucle.cor

# CLEAN
clean: clean-nucle clean-test2013 clean-test2014

.PHONY: clean clean-nucle clean-test2013 clean-test2014
